spring:
    application:
        name: CONFIG-SERVER
    cloud:
        config:
            server:
                git:
                    uri:  https://github.com/spring-cloud-samples/config-repo
server:
    port: 8085

eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost