server:
    port: 8082

spring:
    application:
        name: gateway
    cloud:
      gateway:
        routes:
          - id: order
            uri: lb://ORDER
            predicates:
            - Path=/order/**
            filters:
            - name: CircuitBreaker
              args:
                name: order
                fallbackUri: forward:/orderFallBack
          - id: payment
            uri: lb://PAYMENT
            predicates:
            - Path=/payment/**
            filters:
            - name: CircuitBreaker
              args:
                name: payment
                fallbackUri: forward:/paymentFallBack
    config:
        import:
            configserver:http://localhost:8085