server:
    port: 8081

spring:
    h2:
        console:
            enabled: true
    application:
        name: payment
    config:
        import:
            configserver:http://localhost:8085